version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: ao3_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
    command: --interval 300 --cleanup
    restart: unless-stopped
    networks:
      - ao3_network